### ISSUE TITLE
Gruvbox for XFCE terminal

### ISSUE THREAD

**Issue by joisaac** [hbthen3rd/dotfiles#1]
I'm using ohmyzsh and xubuntu (xfce-terminal). How can I get the same gruvbox colorscheme for my shell setup?

**Comment by hbthen3rd** [comment]
Hi @joisaac, there's a `xfce4-terminal` ports of `gruvbox` here: https://github.com/morhetz/gruvbox-contrib/tree/master/xfce4-terminal

You can also set the colors manually following this palette: https://github.com/morhetz/gruvbox#palette

**Comment by joisaac** [comment]
Thanks a lot!
