### ISSUE TITLE
sketchybar items not updated

### ISSUE THREAD

**Issue by albert-ying** [hbthen3rd/dotfiles#38]
Hi,

Thank you for sharing this fantastic dotfile.

I encountered a weird problem tho:

![CleanShot 2023-10-25 at 00 22 44@2x](https://github.com/hbthen3rd/dotfiles/assets/59846322/b9cf913f-302c-4bae-bd5c-f2bbd90557d3)

as you can see, all the item are not updated.

p.s. I do have yabai and taskwarrior. For example if I run:
```
sh-3.2$ task +PENDING count
```
it returns
```
7
```

But on the sketchybar it doesn't work somehow.

**Comment by albert-ying** [comment]
hmm I just found that it only happens when I use `brew services`. If I just run sketchybar, it works somehow.

**Comment by hbthen3rd** [comment]
@albert-ying  hmm, I'm not sure of what could be happening here.
I've always done `brew services start sketchybar` / `brew services restart sketchybar` for my setup.

For the space indicator issue:
- Make sure you create exactly 7 spaces,
- Sometimes swiping between the spaces can force the indicator to update as well.
- For rendering app icons on the space indicator:
  - Check out this post I made here: https://github.com/FelixKratz/SketchyBar/discussions/12#discussioncomment-6974258.
  - Please note that for the app icons scripts to work:
    - 2 event hooks need to be registered at the end of `yabairc`,
    - 1 custom event hook must be registered inside `sketchybarrc`.

I'm not sure what's happening with `taskwarrior`, but you try the followings:
- Make sure the plugin scripts are allowed to execute:
  `chmod +x .config/sketchybar/plugins/noti_task.sh`
   or `chmod +x .config/sketchybar/plugins/*`
- Try configuring sketchybar with a different nerd font to see if it's a font issue.

**Comment by albert-ying** [comment]
I just figured out! It is a weird environment issue as I have two copy of homebrew (one from intel and one for arm). Thank you so much!
